### PR TITLE
validation for FastBoot, there is no window or document in fastboot env

### PR DESCRIPTION
**Pull request by betocantu93**
Prevents window or document code in fastboot env

Return 0 in fastboot, some people (me) cache the resulting html and without 0, the menu is displayed open in the cached version, so no width solved the issue.

### CODE REVIEW

**Comment by nickschot** [comment]
I'll take a look at this in the weekend. I might want to solve this in the `getWindowWidth` function instead as that prevents any future accidental use.

**Comment by betocantu93** [comment]
Yes, that should work too, I also had to place ua-parser under dependencies in package.json and whitelist it in fastbootDependencies

```
{
  "name": "my-sweet-app",
  "version": "0.4.2",
  "devDependencies": {
    // ...
  },
  "dependencies": {
    "ua-parser-js": "^0.7.14"
  },
  "fastbootDependencies": [
    "ua-parser-js": "^0.7.14"
  ]
}
```

**Comment by nickschot** [comment]
I have reviewed what is necessary for FastBoot support and think this is the only change necessary. All event handlers are only added in a `didInsertElement` hook which isn't called in FastBoot, so all that should be fine. I will soon add FastBoot specific tests.

I am slightly surprised you need to add that dependency as the useragent addon should have FastBoot support. Will take a look at that too. Else we'll have to document it.

Thanks for the PR!

**Comment by nickschot** [comment]
@betocantu93 just to come back to this: when adding fastboot tests I also stumbled upon the ua-parser-js error. Am investigating how best to solve this issue in the addon! See #12 .

**Pull request merged**
